[package]
authors = ["Robin Grell <grellr@hochschule-trier.de>"]
categories = ["internationalization", "gui"]
description = "Keyboard built from scratch with modern features like Next Word Prediction and gesture typing in mind"
license = "MIT"
name = "keyboard"
version = "0.19.0"
edition = "2018"

[dependencies]
gdk = "0.13.0"
gtk = "0.9.0"
cairo-rs = "0.9.1"
relm = "0.20.0"
relm-derive = "0.19.0"
relm-attributes = "0.16.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.13"