[package]
authors = ["Robin Grell <grellr@hochschule-trier.de>"]
categories = ["internationalization", "gui"]
description = "Keyboard built from scratch with modern features like Next Word Prediction and gesture typing in mind"
license = "MIT"
name = "keyboard"
version = "0.19.0"
edition = "2018"

[dependencies]

glib = "0.10.1"
gdk-sys = "0.10.0"
gdk = "0.13.0"
gtk = "0.9.0"
cairo-rs = "0.9.1"
relm = "0.20.0"
relm-derive = "0.19.0"
relm-attributes = "0.16.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.13"
gtk-layer-shell="0.1"
wayland-client = {version="0.27.0", features = ["use_system_lib"]}
wayland-protocols = {version="0.27.0", features = ["client", "unstable_protocols"]}
zwp-virtual-keyboard = "0.1.0"
libc = "0.2.74"
memmap = "0.7.0"