[package]
authors = ["Robin Grell <grellr@hochschule-trier.de>"]
categories = ["internationalization", "gui"]
description = "Keyboard built from scratch with modern features like Next Word Prediction and gesture typing in mind"
license = "MIT"
name = "keyboard"
version = "0.19.0"
edition = "2018"

[dependencies]
libc = "0.2"
memmap = "0.7"
glib = "0.10"
gdk-sys = "0.10"
gdk = "0.13"
gtk = "0.9"
cairo-rs = "0.9"
relm = "0.20"
relm-derive = "0.20"
relm-attributes = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
gtk-layer-shell="0.1"
wayland-client = {version="0.27", features = ["use_system_lib"]}
wayland-protocols = {version="0.27", features = ["client", "unstable_protocols"]}
zwp-virtual-keyboard = "0.1"
input_event_codes_hashmap = "0.1.0"