name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get wayland libs
      run: sudo apt-get install libwayland-dev
    - name: Install GTK libraries
      run: sudo apt-get install libgtk-3-dev
    - name: Get gtk-layer-shell
      run: sudo apt-get install libgtk-layer-shell-dev
    - name: Build
      run: cargo build --verbose --example basic_example
    - name: Run tests
      run: cargo test --verbose --example basic_example